### PR TITLE
Update deps, remove unecessary scripts

### PR DESCRIPTION
**Pull request by umaar**

### CODE REVIEW

**Comment by solidgoldpig** [comment]
This needs more investigation - pretty sure this will break in the console which is not using 12 (and may not be able to)

**Comment by umaar** [comment]
oh? Why would it break the console?

**Comment by solidgoldpig** [comment]
OK, maybe it wouldn't break it, but the console is hard-coded to use 10.15.3 currently.

**Comment by solidgoldpig** [comment]
This definitely breaks stuff in the editor - the flow page at the very least -  but that appears to be because of changes in the runner rather than the Node version bump

**Comment by solidgoldpig** [comment]
Yes, the removal of `pageRender` from `routes-metadata` causes the editor to fall over since it uses it. Mea culpa, I approved that change…

**Pull request closed without merging**
